---
- name: Detect OS by parsing show version
  hosts: all
  gather_facts: false
  connection: ssh

  tasks:
    - name: Run show version
      ansible.builtin.raw: show version
      changed_when: false
      register: show_version
      check_mode: false
      ignore_errors: true

    - name: Parse OS from show version
      ansible.builtin.set_fact:
        detected_os: >
          {% if 'NX-OS' in show_version.stdout %}
            cisco.nxos.nxos
          {% elif 'Arista' in show_version.stdout %}
            arista.eos.eos
          {% elif 'IOS' in show_version.stdout %}
            cisco.ios.ios
          {% else %}
            unknown
          {% endif %}

    - name: Fail if unable to determine OS
      when: detected_os | trim == 'unknown'
      ansible.builtin.fail:
        msg: "Unable to determine device OS."
